services:
  # SQL Server 2019 (same as CPU version)
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: ai-agent-sqlserver-gpu
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Snc@min123
      - MSSQL_PID=Express
    ports:
      - "1436:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./sample_data.sql:/tmp/sample_data.sql
    networks:
      - ai-agent-network
    restart: unless-stopped

  # Ollama with GPU support
  ollama:
    image: ollama/ollama:latest
    container_name: ai-agent-ollama-gpu
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ai-agent-network
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: >
      sh -c "ollama serve & 
             sleep 10 && 
             ollama pull qwen3:8b && 
             wait"

  # Python FastAPI Application (same as CPU version)
  ai-agent:
    build: .
    container_name: ai-agent-app-gpu
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=Server=sqlserver,1433;Database=JOBORDER;Uid=sa;Pwd=Snc@min123;TrustServerCertificate=yes;
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - sqlserver
      - ollama
    networks:
      - ai-agent-network
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app

volumes:
  sqlserver_data:
  ollama_data:

networks:
  ai-agent-network:
    driver: bridge